stages:
  - push:readme
  - build:docker

variables:
  IMAGE_NAME_DOCKERHUB: "index.docker.io/bruceforce/bw_backup"
  # see https://gitlab.com/gitlab-org/gitlab-runner/issues/4501
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  # See https://github.com/docker/buildx/releases
  BUILDX_VERSION: v0.5.1
  BUILDX_ARCH: linux-amd64

.docker_login: &docker_login
  docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

.dockerhub_login: &dockerhub_login
  docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD" $DOCKERHUB_REGISTRY

.docker_build_template: &docker_build
  stage: build:docker
  image: docker:latest
  services:
    - name: docker:dind
      command: ["--experimental"]
  tags:
    - shared
  before_script:
    - apk add curl
    - mkdir -p ~/.docker/cli-plugins
    - curl -sSLo ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/$BUILDX_VERSION/buildx-$BUILDX_VERSION.$BUILDX_ARCH 
    - chmod +x ~/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker context create my-context
    - docker buildx create --use my-context
    - docker info

build_master:
  <<: *docker_build
  script:
    - *docker_login
    - *dockerhub_login
    #- docker build --pull -t "$IMAGE_NAME" -t "$IMAGE_NAME_DOCKERHUB:${CI_COMMIT_TAG:-latest}" .
    - docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_TAG:-latest}" -t "$IMAGE_NAME_DOCKERHUB:${CI_COMMIT_TAG:-latest}" .
    #- docker push "$IMAGE_NAME"
    #- docker push "$IMAGE_NAME_DOCKERHUB:${CI_COMMIT_TAG:-latest}"
  only:
    refs:
      - master
      - tags
    changes:
      - Dockerfile
      - backup.sh
      - entrypoint.sh

build:
  <<: *docker_build
  script:
    - *docker_login
    #- docker build --pull -t "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/bw_backup:${CI_COMMIT_TAG:-latest}" .
    - ls -la
    - docker run 
      -v $(pwd)/README.md:/data/README.md:ro
      -e DOCKER_USER=$DOCKERHUB_USER 
      -e DOCKER_PASS=$DOCKERHUB_PASSWORD 
      chko/docker-pushrm --file /data/README.md docker.io/bruceforce/bw_backup
    - docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" .
    #- docker push "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/bw_backup:${CI_COMMIT_TAG:-latest}"
  except:
    - master

